project/post/urls.py
from django.urls import path
from . import views


app_name = "post"
urlpatterns = [
    path("", views.home, name="index"),
    path("post_list/", views.post_list, name="post_list"),
    path("post_detail/<int:id>/", views.post_detail, name="post_detail"),
    path("create_post/", views.create_post, name="create_post"),
    path("post_vote/<int:id>/", views.post_vote, name="post_vote"),
    path("comments_vote/<int:id>/", views.comment_vote, name="comment_post"),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from pather.views import handler


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', handler),
    path('post/', include('post.urls')),
]

project/pather/models.py
from django.db import models

# Create your models here.

project/post/models.py
from django.db import models

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=100)
    caption = models.TextField(blank=True, null=True)
    is_publish = models.BooleanField(default=False)
    votes = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey("Post", on_delete=models.CASCADE)
    text = models.TextField()
    votes = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.post} --- {self.text[:7]}..."

project/pather/views.py
from django.shortcuts import render
from project.settings import INSTALLED_APPS
# Create your views here.


def handler(request):
    apps_all = [app for app in INSTALLED_APPS if "apps" in app]
    apps = list()
    for app in apps_all:
        ls = list(app.split("."))
        apps.append(ls[0])

    context = {
        "apps":apps
    }
    return render(request, "pather/index.html", context=context)

project/post/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.http import HttpResponse
from django.template import loader
from django.db.models import F
from .models import Post, Comment
from django.urls import reverse
# Create your views here.


def home(request):
    template = loader.get_template("post/home.html")
    return HttpResponse(template.render())


def post_list(request):
    posts = get_list_or_404(Post)
    template = loader.get_template("post/post_list.html")
    return HttpResponse(template.render(context={"posts": posts})) 
    # return render(request, "post/post_list.html", {"posts": posts})

def post_detail(request, id):
    post = get_object_or_404(Post, id=id)
    if request.method == "POST":
        selected_post = request.POST["like"]
        if post.id == int(selected_post):
            post.votes = F("votes") + 1
            post.save()
            return redirect(reverse("post:post_detail", args=(post.id,)))
    return render(request, "post/post_detail.html", context={"post":post})

def create_post(request):
    if request.method == "POST":
        title = request.POST.get("title")
        caption = request.POST.\
        get("caption")
        post = Post(title=title, caption=caption)
        post.save()
        post_id = post.id
        return HttpResponse("your post it's created at :\
             <br>\
             <a href=\"/post/post_detail/%s\"> link </a>"%(post_id))
    else:
        return render(request, "post/form.html")    
    

def post_vote(request, id):
    post = get_object_or_404(Post, id=id)
    post.votes = F("votes") + 1
    post.save()
    return redirect("/post/post_list")



def comment_vote(request, id):
    post = get_object_or_404(Post, id=id)
    try:
        comment = post.comment_set.get(id = request.POST.get("comment"))
    except Exception:
        return render(
            request,
            "post/post_detail.html",
            {
                "post" : post,
                "error" : "you can't like this comment",
            }
        )
    else:
        comment.votes += 1
        comment.save()

        return redirect(reverse("post:post_detail", args=(post.id,)))

project/pather/templates/pather/index.html
<html>
    <head>

    </head>
    <body>
        <center>
            <h1>Hello welcome to my website</h1>
            <p> if you want use this website you sould go to some app and use that app</p>
            <hr>
        </center>
        <h2>there are some apps here to use :</h2>
        <ul>
            {% for app in apps %}
                <li> <a href="{% url app|add:":index" %}"> {{app}} </a></li>
            {% endfor %}
        </ul>
    </body>
</html>

project/post/templates/post/form.html
{% extends "post/index.html" %}

{% block content %}
<form action="{% url "post:create_post" %}" method="post">
    {% csrf_token %}
    <input type="text" name="title">
    <br>
    <input type="text" name="caption">
    <br>
    <input type="submit">
</form>
{% endblock content %}

project/post/templates/post/home.html
{% extends "post/index.html" %}

{% block content %}
<h1> Hello welcome to this website </h1>
<h2> You can see posts in this website </h2>
<hr>
<ul>
    <li> <a href="{% url "post:post_list" %}"> for see posts </a> </li>
    <li> <a href="{% url "post:create_post" %}"> for create post </a> </li>
</ul>
{% endblock content %}

project/post/templates/post/index.html
<html>
    <head>
        <style>
            body{
                background-color: black;
                color: white;
            }
            a{
                color: rgb(57, 212, 153);
            }

            input{
                padding: 5px;
                margin: 10px;
            }
        </style>
    </head>
    <body>
        {% block content %}
        {% endblock content %}

        {% block script %}
        {% endblock script %}
    </body>
</html>

project/post/templates/post/post_detail.html
{% extends "post/index.html" %}


{% block content %}
<h1 style="text-align:center; color:white;"> you are in post detail page </h1>

<hr>

<form action="" method="post" style="padding:100px">
    {% csrf_token %}
    <fieldset style="color:white;">
        <legend> {{post.title}} </legend>
        <p> {{post.caption}} </p>
    <small>{{post.created_at}}</small>
    <ol>
    {% for comment in post.comment_set.all %}
        <li style="color:green ;"> {{comment}} <span> {{comment.votes}} </span> </li>
        <label for="vote" style="color:grey;"> like this post </label>
        <input type="radio" name="vote">
        <input type="submit" value={{comment.id}}>
        <br>
    {% endfor %}
    </ol>
    <p>Likes : {{post.votes}}</p>
    <div>
        <button name="like" type="submit" value="{{post.id}}" style="width: 100px; height: 50px;" id="like">like post </button>
        <button type="text" style="width: 100px; height: 50px;"> <a style="text-decoration:none; color:black;" href="{% url 'post:post_list' %}"> back to posts </a> </button>
    </div>
    </fieldset>
</form>
{% endblock content %}

project/post/templates/post/post_list.html
{% extends "post/index.html" %}


{% block content %}
<h3>In this page you can see posts</h3>
<hr>

<ul>
    {% for post in posts %}
    {% if post.is_publish == True %}
        <li>
            <a href="{% url 'post:post_detail' post.id %}">
                <p>{{ post.title }}  <span>likes : {{post.votes}}</span></p>
                <button style="background-color: green; border: none;"> <a style="text-decoration:none; color: white;" href="{% url "post:post_vote" post.id %}"> like </a> </button>
            </a>
        </li>
    {% endif %}
    {% empty %}
        <li>No posts found.</li>
    {% endfor %}
</ul>
{% endblock content %}